# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQMmbo2v3dZ_komMgDhDgT6c0uPpWilx
"""

import numpy as np
import matplotlib.pyplot as plt

"""F(x) = alpha / 1 + exponential ** (-b * x)"""

x = np.linspace(-4,8,42)
alpha = 23
beta = 2

num = alpha
den = 1 + np.exp(-beta * x)
fx = num / den
plt.plot(x,fx,'-s')
plt.show()

"""Experimenting with f string in python print()

---
It seems that a number after : will make space. while :.(number)f will indicate the decimal point

"""

pi = 22/7
print(f'{pi}, {pi:.6f}')

"""Checking for time taken for the code to run

---


"""

import time
 clockStart = time.time()
 # some code here...
 compTime = time.time() - clockStart